name: liquid_flutter_emd_theme
description: EMD theme for liquid flutter
repository: https://github.com/emdgroup-liquid/liquid-flutter-emd-theme
version: 0.0.1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  liquid_flutter: ^18.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: EMD
      fonts:
        - asset: lib/fonts/EMD.ttf
    - family: LiquidIcons
      fonts:
        - asset: lib/fonts/LiquidIcons.ttf
